---
- name: "copy ksm template"
  template:
    src: kube_state_metrics_alerts.yml.j2
    dest: /tmp/kube_state_metrics_alerts.yml

- name: Create ksm alerts
  shell: "oc create -f /tmp/kube_state_metrics_alerts.yml -n {{ middleware_monitoring_namespace }}"
  register: create_ksm_alerts
  failed_when: create_ksm_alerts.stderr != '' and 'already exists' not in create_ksm_alerts.stderr
  changed_when: create_ksm_alerts.rc == 0
