---
- name: Create project namespace
  shell: oc new-project {{ enmasse_namespace }} --description="AMQ Online Infrastructure"
  register: namespace_exists
  failed_when: namespace_exists.stderr != '' and 'already exists' not in namespace_exists.stderr and '(Forbidden)' not in namespace_exists.stderr
  changed_when: namespace_exists.rc == 0
- name: Select project namespace
  shell: oc project {{ enmasse_namespace }}