---
backup_namespace: "openshift-integreatly-backups"
aws_s3_backup_secret_name: 's3-credentials'

backup_s3_aws_access_key: ""
backup_s3_aws_secret_key: ""
backup_s3_aws_bucket: ""

component_backup_secret_namespace: '{{ backup_namespace }}'
backup_resources_cluster:
  - "{{backup_resources_location}}/rbac/role.yaml"

backup_expected_cronjobs: |
  {
    "{{backup_namespace}}": [
      "3scale-mysql-backup",
      "3scale-postgres-backup",
      "3scale-redis-backup",
      "codeready-postgres-backup",
      "codeready-pv-backup",
      "enmasse-postgres-backup",
      "enmasse-pv-backup",
      "fuse-postgres-backup",
      "resources-backup",
      "launcher-postgres-backup"
    ],
    "{{eval_rhsso_namespace}}": [
      "daily-at-midnight"
    ]
  }

sso_expected_cronjobs: |
  {
    "{{eval_user_rhsso_namespace}}": [
      "daily-at-midnight"
    ]
  }

monitoring_namespace: "{{ns_prefix | default('')}}middleware-monitoring"
